---
# tasks file for ssh
- name: Add a new user
  user:
    name: "{{ sshd_provision_user }}"
  become: yes
  when: build is false

- name: Add user to the sudoers
  copy:
    dest: "/etc/sudoers.d/{{ sshd_provision_user }}"
    content: "{{ sshd_provision_user }}  ALL=(ALL)  NOPASSWD: ALL"
  become: yes
  when: build is false

- name: Deploy SSH Key
  authorized_key:
    user: "{{ sshd_provision_user }}"
    key: "{{ lookup('file', sshd_provision_user_authorized_key) }}"
    state: present
  become: yes
  when: build is false

- name: Apply sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart ssh
  become: yes

- name: Add build exception
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    insertafter: EOF
    line: "{{ item }}"
    when: build is true
    with_items:
      - "Match user vagrant"
      - "  PasswordAuthentication yes"